### ISSUE TITLE
Simpler folklore format.

### ISSUE THREAD

**Issue by barrucadu** [HackSoc/folklore#1]
In the interests of funniness (eg, generating `fortune` data files) and practicality (modifying HTML templates) it would be nice to have the folklore in a non-HTML format.

I initially thought cookie-jar format would work, but folklore has associated metadata (validity and a possible reference), so record-jar or mboxo would work better. mboxo would probably be nicer:

```
Type: Fb
The horrible grey buildings used to be a lovely white. (And only started to go grey in the 70's.)

Type: Tb
The horrible grey buildings used to be a lovely grey.

Type: F
Ref:  buildings.html
The concrete panels were designed with a life expectancy of 30 years. (This was in 1963 or so).

etc
```

`Type` starts a new entry. If the `Ref` field starts with `[a-z]://` it can be interpreted as an absolute url. Each section could then have its own file, and there could be compilers to templated HTML and to cookie-jar.

**Comment by Taneb** [comment]
Issue with that format is that there are sometimes subfacts, like "F.
Plans for underground car park abandoned at some stage due to weight of books necessitating stronger foundations. (T. It was found to cost less to build the library on the hillside.)"

**Comment by barrucadu** [comment]
We could do something YAMLy:

``` .yaml
- type: F
  fact: Plans for underground car park abandoned at some stage due to weight of books necessitating stronger foundations.

  sub:
   - type: T
     fact: It was found to cost less to build the library on the hillside.

- type: Fb
  fact: The horrible grey buildings used to be a lovely white. (And only started to go grey in the 70's.)
```

**Comment by barrucadu** [comment]
Also, for pages which aren't a list of folklore entries, we can just use markdown.

**Comment by Taneb** [comment]
This raises the question, will we pre-compile these to HTML? Will we do it on the fly? What will we use for the compiler?

**Comment by barrucadu** [comment]
Definitely pre-compile. I was thinking Hakyll, but given the simplicity of the inputs and outputs, we could easily roll our own thing with yaml and pandoc directly.

**Comment by barrucadu** [comment]
Another possibility:

``` .yaml
- F: Plans for underground car park abandoned at some stage due to weight of books necessitating stronger foundations.

  sub:
   - T: It was found to cost less to build the library on the hillside.

- Fb: The horrible grey buildings used to be a lovely white. (And only started to go grey in the 70's.)
```

This is nice as it's pretty close to the original format, just making subfacts and references more explicit.

**Comment by barrucadu** [comment]
Let's go with the latest YAML suggestion, as it lets us add arbitrary key/value data to entries.

More formally, the format is now this:
1. A folklore file consists of a bulleted list of entries.
2. An entry consists of:
   1. A single "T", "Tb", "F", "Fb", or "U" key, the value for which is the text of the fact.
   2. An optional "ref" key, the value of which is a reference containing further information. For HTML hyperlinking purposes:
      - If the value starts with `[a-z]://` it is interpreted as an absolute URL.
      - Otherwise it is interpreted as the name of a page.
   3. An optional "sub" key, the value of which is a bulleted list of entries.
   4. Any other keys are optional and do not have a meaning determined here.
